# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    providers:
        my_security_provider:
            mongodb:
                class: AppBundle\Document\User
                property: email


    encoders:
        AppBundle\Document\User:
            algorithm: bcrypt


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: my_security_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/hit, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
