---
- name: Ensure that Nginx PPA is added
  apt_repository: repo=ppa:nginx/stable state=present
  become: yes

- name: Install Nginx package
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nginx
  become: yes

- name: Disable the default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  become: yes
  notify: restart nginx

- name: Configure virtual host
  template:
    dest: /etc/nginx/sites-enabled/{{ nginx_site }}.conf
    src: site.conf.j2
  become: yes
  notify: restart nginx
