---
- hosts: all

  vars:
    app:
      name: contact
    project_root: /vagrant
    timezone: UTC

    supervisor_inet_http_server_enabled: true
    supervisor_programs_present:
      foo:
        command: 'beanstalkd'

  pre_tasks:
    - name: Install build essential
      apt: package=build-essential state=latest

  roles:
    - yatesr.timezone
    - php
    - nginx
    - mongodb
    - geerlingguy.composer
    - geerlingguy.mailhog
    - pip
    - beanstalkd
    - tersmitten.supervisor
    - application
