---
- hosts: all

  vars:
    app:
      name: contact
    project_root: /vagrant
    timezone: UTC

  pre_tasks:
    - name: Install build essential
      apt: package=build-essential state=latest

  roles:
    - yatesr.timezone
    - php
    - nginx
    - mongodb
    - geerlingguy.composer
    - geerlingguy.mailhog
    - application
