services:

  app.handler.email_handler:
    class: AppBundle\Handler\EmailHandler
    arguments:
      - '@mailer'
      - '@twig'
      - '%handler_email%'
      - '@logger'
    tags:
      - { name: app.handler, alias: email_handler }
